export const baseUrl = 'https://liquorapps.com/Bcapi/api/';
export enum UrlNames {
    GetStoreHome = 'Store/StoreGetHome',
    LoginCustomer = 'Login/LoginCustomer',
    ProductGetList = 'Product/ProductGetList',
    ProductGetDetails = 'Product/ProductGetDetail',
    EventGetDetails = 'Event/EventGetDetail',
    FavoriteProductUpdate = 'Product/FavoriteProductUpdate',
    RecipeGetList = 'Recipe/RecipeGetList',
    RecipeGetDetail = 'Recipe/RecipeGetDetail',
    CartAddItem = 'Cart/CartAddItem',
    CartRemoveItem = 'Cart/CartRemoveItem',
    CartGetDetail = 'Cart/CartGetDetail',
    ReviewRatingInsert = 'Review/ReviewRatingInsert',
    OrderGetList = 'Order/OrderGetList',
    OrderInsert = 'Cart/OrderInsert',
    CartUpdate = 'Cart/CartUpdate',
    CustomerAddressGetList = 'Customer/CustomerAddressGetList',
    AddressInsert = 'Customer/AddressInsert',
    AddressDelete = 'Customer/AddressDelete',
    AddressUpdate = 'Customer/AddressUpdate',
    ProfileGetDetail = 'Customer/ProfileGetDetail',
    CustomerProfileUpdate = 'Customer/CustomerProfileUpdate',
    CustomerPaymentMethodGetList = 'Customer/CustomerPaymentMethodGetList'
}
